//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Registration
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        
        public int user_id { get; set; }

        [Required]
        public string user_name { get; set; }
        [MaxLength(50)]
        public string user_mail { get; set; }
        [MaxLength(50)]
        public string password { get; set; }
        public Nullable<int> age { get; set; }
    }
}
