//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login_Redirection.ValidationServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ValidationServiceRef.UserValidationServiceSoap")]
    public interface UserValidationServiceSoap {
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoginUser", ReplyAction="*")]
        Login_Redirection.ValidationServiceRef.LoginUserResponse LoginUser(Login_Redirection.ValidationServiceRef.LoginUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoginUser", ReplyAction="*")]
        System.Threading.Tasks.Task<Login_Redirection.ValidationServiceRef.LoginUserResponse> LoginUserAsync(Login_Redirection.ValidationServiceRef.LoginUserRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegisterUser", ReplyAction="*")]
        Login_Redirection.ValidationServiceRef.RegisterUserResponse RegisterUser(Login_Redirection.ValidationServiceRef.RegisterUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegisterUser", ReplyAction="*")]
        System.Threading.Tasks.Task<Login_Redirection.ValidationServiceRef.RegisterUserResponse> RegisterUserAsync(Login_Redirection.ValidationServiceRef.RegisterUserRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginUser", Namespace="http://tempuri.org/", Order=0)]
        public Login_Redirection.ValidationServiceRef.LoginUserRequestBody Body;
        
        public LoginUserRequest() {
        }
        
        public LoginUserRequest(Login_Redirection.ValidationServiceRef.LoginUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public LoginUserRequestBody() {
        }
        
        public LoginUserRequestBody(string name, string password) {
            this.name = name;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public Login_Redirection.ValidationServiceRef.LoginUserResponseBody Body;
        
        public LoginUserResponse() {
        }
        
        public LoginUserResponse(Login_Redirection.ValidationServiceRef.LoginUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool LoginUserResult;
        
        public LoginUserResponseBody() {
        }
        
        public LoginUserResponseBody(bool LoginUserResult) {
            this.LoginUserResult = LoginUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterUser", Namespace="http://tempuri.org/", Order=0)]
        public Login_Redirection.ValidationServiceRef.RegisterUserRequestBody Body;
        
        public RegisterUserRequest() {
        }
        
        public RegisterUserRequest(Login_Redirection.ValidationServiceRef.RegisterUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pass;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int age;
        
        public RegisterUserRequestBody() {
        }
        
        public RegisterUserRequestBody(string name, string pass, string email, int age) {
            this.name = name;
            this.pass = pass;
            this.email = email;
            this.age = age;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public Login_Redirection.ValidationServiceRef.RegisterUserResponseBody Body;
        
        public RegisterUserResponse() {
        }
        
        public RegisterUserResponse(Login_Redirection.ValidationServiceRef.RegisterUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int RegisterUserResult;
        
        public RegisterUserResponseBody() {
        }
        
        public RegisterUserResponseBody(int RegisterUserResult) {
            this.RegisterUserResult = RegisterUserResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UserValidationServiceSoapChannel : Login_Redirection.ValidationServiceRef.UserValidationServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserValidationServiceSoapClient : System.ServiceModel.ClientBase<Login_Redirection.ValidationServiceRef.UserValidationServiceSoap>, Login_Redirection.ValidationServiceRef.UserValidationServiceSoap {
        
        public UserValidationServiceSoapClient() {
        }
        
        public UserValidationServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserValidationServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserValidationServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserValidationServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Login_Redirection.ValidationServiceRef.LoginUserResponse Login_Redirection.ValidationServiceRef.UserValidationServiceSoap.LoginUser(Login_Redirection.ValidationServiceRef.LoginUserRequest request) {
            return base.Channel.LoginUser(request);
        }
        
        public bool LoginUser(string name, string password) {
            Login_Redirection.ValidationServiceRef.LoginUserRequest inValue = new Login_Redirection.ValidationServiceRef.LoginUserRequest();
            inValue.Body = new Login_Redirection.ValidationServiceRef.LoginUserRequestBody();
            inValue.Body.name = name;
            inValue.Body.password = password;
            Login_Redirection.ValidationServiceRef.LoginUserResponse retVal = ((Login_Redirection.ValidationServiceRef.UserValidationServiceSoap)(this)).LoginUser(inValue);
            return retVal.Body.LoginUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Login_Redirection.ValidationServiceRef.LoginUserResponse> Login_Redirection.ValidationServiceRef.UserValidationServiceSoap.LoginUserAsync(Login_Redirection.ValidationServiceRef.LoginUserRequest request) {
            return base.Channel.LoginUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<Login_Redirection.ValidationServiceRef.LoginUserResponse> LoginUserAsync(string name, string password) {
            Login_Redirection.ValidationServiceRef.LoginUserRequest inValue = new Login_Redirection.ValidationServiceRef.LoginUserRequest();
            inValue.Body = new Login_Redirection.ValidationServiceRef.LoginUserRequestBody();
            inValue.Body.name = name;
            inValue.Body.password = password;
            return ((Login_Redirection.ValidationServiceRef.UserValidationServiceSoap)(this)).LoginUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Login_Redirection.ValidationServiceRef.RegisterUserResponse Login_Redirection.ValidationServiceRef.UserValidationServiceSoap.RegisterUser(Login_Redirection.ValidationServiceRef.RegisterUserRequest request) {
            return base.Channel.RegisterUser(request);
        }
        
        public int RegisterUser(string name, string pass, string email, int age) {
            Login_Redirection.ValidationServiceRef.RegisterUserRequest inValue = new Login_Redirection.ValidationServiceRef.RegisterUserRequest();
            inValue.Body = new Login_Redirection.ValidationServiceRef.RegisterUserRequestBody();
            inValue.Body.name = name;
            inValue.Body.pass = pass;
            inValue.Body.email = email;
            inValue.Body.age = age;
            Login_Redirection.ValidationServiceRef.RegisterUserResponse retVal = ((Login_Redirection.ValidationServiceRef.UserValidationServiceSoap)(this)).RegisterUser(inValue);
            return retVal.Body.RegisterUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Login_Redirection.ValidationServiceRef.RegisterUserResponse> Login_Redirection.ValidationServiceRef.UserValidationServiceSoap.RegisterUserAsync(Login_Redirection.ValidationServiceRef.RegisterUserRequest request) {
            return base.Channel.RegisterUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<Login_Redirection.ValidationServiceRef.RegisterUserResponse> RegisterUserAsync(string name, string pass, string email, int age) {
            Login_Redirection.ValidationServiceRef.RegisterUserRequest inValue = new Login_Redirection.ValidationServiceRef.RegisterUserRequest();
            inValue.Body = new Login_Redirection.ValidationServiceRef.RegisterUserRequestBody();
            inValue.Body.name = name;
            inValue.Body.pass = pass;
            inValue.Body.email = email;
            inValue.Body.age = age;
            return ((Login_Redirection.ValidationServiceRef.UserValidationServiceSoap)(this)).RegisterUserAsync(inValue);
        }
    }
}
